server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  # 连接码云远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cao_shi_peng/springcloud-config.git #注意是https的而不是ssh
# 通过 config-server可以连接到git，访问其中的资源以及配置~

# 不加这个配置会报Cannot execute request on any known server 这个错：连接Eureka服务端地址不对
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
